fix: npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require(os).homedir()` instead. (#3261)
* fix: npm run chore:update-deps error fix

1. update_deps.sh not exist. 
2. use `sh ./scripts/reinstall_deps.sh` to run command on git-bash in windows.

* fix: import umi-ui fail error

require("umi-ui") Error: Cannot find module 'umi-ui'

* fix: npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require(os).homedir()` instead.